# Generated by Django 3.0.8 on 2020-08-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200803_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
