# Generated by Django 3.0.8 on 2020-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_remove_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='tag',
            field=models.CharField(choices=[('personal', 'Personal'), ('client', 'Client')], max_length=50),
        ),
    ]
